### ISSUE TITLE
Each new BEAM instance always gives the same sequence of values. How to prevent this?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [jj1bdx/exs64#6]
@jj1bdx Hi,

Please each new BEAM instance always gives the same sequence of random values for `exs64:uniform(N).`

How can I prevent this?

Example: 
`uniform(900000)` always gives same sequence: `114849, 855038, 232204, 496223, ...`

Thanks.

**Comment by jj1bdx** [comment]
If you are using 18.x, try `rand:uniform/1` instead; `rand:uniform/1` initializes with a set of monotonic time values when it is called for the first time after the BEAM is initialized. You can choose exs64 in the rand module, though the default algorithm is exsplus (or exsplus116), which is as good as exs64 for most purposes.

If you are using 17.x or earlier, always call the seeding function as follows _before_ using the function:

``` erlang
<<A:32, B:32, C:32>> = crypto:rand_bytes(12), exs64:seed(A, B, C)
```

**Comment by CharlesOkwuagwu** [comment]
Thanks!

**Comment by CharlesOkwuagwu** [comment]
@jj1bdx

Please I am trying to build a token system that issues unique random 6-digit codes. Each code has a life-span of 3mins after which it may be reused. Codes range from 100000-999999 i.e. 900,000 possible codes.

Problems: I always have some collisions, and the more tokens issued the higher the collisions.
```
Iex(1)> Enum.uniq(for a<- 1..100000,do: :rand.uniform(900000)) |> length
94693
```
Is there a way to skew the random function such that it ignores previously issues values? 

I have tried to use a Map to store already assigned values, but that is very slow, as i need to do a lookup each time before i can find a token that has not been used. I even need multiple lookups to find a free token, as more tokens are issued.

How would such a solution run effectively on multiple nodes, so  that one users request to generate a token will not block another concurrent user - and each is guaranteed to have a unique token?

My idea:

Run `N BEAM instances`, each handling `1/N` of the Token range.
Use a router to decide which instance handles next request,  using `request_count rem N` as my routing function

**Comment by jj1bdx** [comment]
Issue closed.
